# Generated by Django 4.0.4 on 2022-04-19 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('point_de_depart', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('alt_depart', models.FloatField(verbose_name='Altitude (m)')),
                ('alt_min', models.FloatField(verbose_name='Altitude minimale (m)')),
                ('alt_max', models.FloatField(verbose_name='Altitude maximale (m)')),
                ('deniv_pos_cumul', models.FloatField(verbose_name='Denivele positif cumule (m)')),
                ('deniv_neg_cumul', models.FloatField(verbose_name='Denivele negatif cumule (m)')),
                ('duree', models.IntegerField(verbose_name='Durée (h)')),
                ('difficulte', models.IntegerField(choices=[(5, 'Impossible'), (4, 'Epuisant'), (3, 'Normal'), (2, 'Promenade'), (1, 'Repos')])),
            ],
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateur', models.CharField(max_length=200)),
                ('date_sortie', models.DateTimeField(verbose_name='date sortie')),
                ('duree', models.IntegerField(verbose_name='Durée (h)')),
                ('nombre_personnes', models.IntegerField(verbose_name='Nombre de personnes')),
                ('experience', models.IntegerField(choices=[(1, 'Debutants'), (2, 'Mixte'), (3, 'Experimentes')])),
                ('meteo', models.IntegerField(choices=[(1, 'Mauvaise'), (2, 'Moyenne'), (3, 'Bonne')])),
                ('difficulte', models.IntegerField(choices=[(5, 'Impossible'), (4, 'Epuisant'), (3, 'Normal'), (2, 'Promenade'), (1, 'Repos')])),
                ('itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraires.itineraire')),
            ],
        ),
    ]
